app:
  build: ./hackathon-app
  volumes:
    - /var/log/hackathon/nginx:/var/log/nginx
    - /var/log/hackathon/php-fpm:/var/log/php5-fpm
    - /var/www/project:/var/www/project
  environment:
    TOPFACE_USER: whatever
    PLATFORM: dev
  ports:
    - 80:80
    - 443:443
    - 9000:9000
  links:
    - redis
    - redis2
    - redis3
    - pg
    - stat
redis:
  image: redis:2.8
  volumes:
    - /var/db/redis:/data
redis2:
  image: redis:2.8
  volumes:
    - /var/db/redis2:/data
redis3:
  image: redis:2.8
  volumes:
    - /var/db/redis3:/data
pg:
  image: sameersbn/postgresql:9.4
  volumes:
    - /var/db/postgresql/:/var/lib/postgresql/
  environment:
    DB_USER: hackathon
    DB_PASS: sosecretpassword
    DB_NAME: hackathon
  ports:
    - 5432:5432
fatwood:
  build: ../fatwood
  command: -listen 0.0.0.0:15000 -config /configs/quimby.json
  ports:
    - 15000:15000
  links:
    - redis3
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: mysqlsecretrootpassord
    MYSQL_USER: hackathon
    MYSQL_PASSWORD: hackathonpassword
    MYSQL_DATABASE: minCohortDb
  volumes:
    - /var/db/mysql:/var/lib/mysql
stat:
  build: ./hackathon-stat
  ports:
    - 13200:13200
  links:
    - mysql
